[WIP] Correspondence to v2
0xhokusai/hokusai-stoplight-docs pull request #45
Opened 2022-03-08 10:30 UTC by silmin

## 関連リンク(Slack, Notion)や GitHub Issue

- https://www.notion.so/0xhokusai/Batch-Mint-API-Docs-61f487d81c094397a0aa4d4459336809

## やったこと

- ドキュメントへのv2情報の追加
- 内部のサンプルをv2仕様に
  - tabにしてv2優先で表示

2022-03-10 07:14 UTC, 0xKagatani requested changes

2022-03-10 07:14 UTC, 0xKagatani commented on docs/ja/authentication.md
>  All endpoints must include the `key` parameter with the API key.
この英語記述は削除していいかも？

2022-03-10 10:49 UTC, silmin commented on docs/ja/sample-app.md
> +また、Hokusai APIででMeta Transactionを利用する際には、[`transfer`](../../reference/swagger-v2.yaml#transfer)エンドポイントを利用します。
ありがとうございます！
なんか今回の差分以外ちゃんとやらないといけない部分が反映されてないって感じですね。
一緒にやっちゃいます！

2022-03-10 10:52 UTC, silmin commented on docs/ja/sample-app.md
> +また、Hokusai APIででMeta Transactionを利用する際には、[`transfer`](../../reference/swagger-v2.yaml#transfer)エンドポイントを利用します。
この「Hokusai」表記って、ドキュメント左下のココも統一した方がいいですかね？

![image](https://user-images.githubusercontent.com/32303837/157647056-e0f5d050-87f0-4e05-9b2b-536a68c1c46c.png)

2022-03-10 11:28 UTC, 0xKagatani commented on docs/ja/sample-app.md
> +また、Hokusai APIででMeta Transactionを利用する際には、[`transfer`](../../reference/swagger-v2.yaml#transfer)エンドポイントを利用します。
ありがとうございます！
「Hokusai」統一でいきましょう！

2022-03-10 13:10 UTC, silmin commented on docs/ja/authentication.md
>  All endpoints must include the `key` parameter with the API key.
削除しました！

2022-03-11 01:27 UTC, 0xKagatani approved these changes
確認しました！大丈夫だと思います！ありがとうございます＾＾

2022-03-11 05:47 UTC, silmin commented
これに関して、API側の変更が少しあるので、今日の夜中までには修正してcommitします

2022-03-13 21:21 UTC, Jaguarmouse commented
@silmin LGTMなのでマージしてしまいます！ありがとうございます！

2022-03-13 21:21 UTC, merged